//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocPrescriptionRecord
    {
        public long No { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> RecordNo { get; set; }
        public Nullable<long> PresId { get; set; }
        public string Rx { get; set; }
        public string Sig { get; set; }
        public string Disp { get; set; }
    
        public virtual MedicalRecord MedicalRecord { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
