//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicalRecord()
        {
            this.DocPrescriptionRecords = new HashSet<DocPrescriptionRecord>();
            this.Medications = new HashSet<Medication>();
        }
    
        public long RecordNo { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string Pat_Id { get; set; }
        public string Phys_id { get; set; }
        public string ActivityName { get; set; }
        public string RecordDetails { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocPrescriptionRecord> DocPrescriptionRecords { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medication> Medications { get; set; }
    }
}
