//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medication
    {
        public long MidNo { get; set; }
        public Nullable<long> RecordNo { get; set; }
        public Nullable<System.DateTime> RecordedDate { get; set; }
        public string MedicationDesc { get; set; }
    
        public virtual MedicalRecord MedicalRecord { get; set; }
    }
}
