//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public string Pat_Id { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public string Middle { get; set; }
        public string Gender { get; set; }
        public string CivilStat { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public string Occupation { get; set; }
        public string Company { get; set; }
        public string AddStreetBrgy { get; set; }
        public string Muncity { get; set; }
        public string Province { get; set; }
        public string ContactCell { get; set; }
        public string ContactPhone { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string BType { get; set; }
        public string GuardianName { get; set; }
        public string GuardianContact { get; set; }
        public string GuardianRelation { get; set; }
        public Nullable<System.DateTime> DateRegister { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
