//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMIS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Physician
    {
        public int No { get; set; }
        public string Id { get; set; }
        public Nullable<int> Phys_id { get; set; }
    
        public virtual Physician Physician { get; set; }
    }
}
